<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <CheckEolTargetFrameworks>false</CheckEolTargetFrameworks>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <RootNamespace>Comms</RootNamespace>
    <AssemblyName>Comms</AssemblyName>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <CheckEolTargetFrameworks>false</CheckEolTargetFrameworks>
  </PropertyGroup>
</Project>